version: '2'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
      args:
        app_version: ${APP_VERSION}
    environment:
      CLUSTER_GROUP_NAME: portfolio-service
      CLUSTER_GROUP_PASSWORD: password
  test:
    image: dpaws/microtrader-test
    links:
      - app
    environment:
      CLUSTER_GROUP_NAME: portfolio-service
      CLUSTER_GROUP_PASSWORD: password
    command:
      - mvn
      - test
      - -Dtest=PortfolioServiceTest
      - -Dvertx.hazelcast.config=/app/conf/cluster.xml
